### ISSUE TITLE
Incorrect References to "New-Header."

### ISSUE THREAD

**Issue by tommymaynard** [umn-microsoft-automation/UMN-Grouper#13]
Sorry, I don't have the time to get involved in updating the module, _but_ I did want to point out something I noticed when working with this module today (for the first time ever [it's awesome by the way]). There are several references to "New-Header" in the module file (.psm1). These should be referencing the "New-GrouperHeader" function.

**Comment by kylecweeks** [comment]
Updated flavor text.
